language: node_js
node_js:
  - "lts"
  - "node"
  - "8"
cache:
  yarn: true
  directories:
    - "node_modules"
install:
  - yarn install --frozen-lockfile
script:
- yarn run lint
- yarn run test
- yarn run build 